### ISSUE TITLE
Has anyone had any success with this bot?

### ISSUE THREAD

**Issue by siyadgedi** [VVNoodle/PS5bot#9]
I'm trying to get one PS5 for myself and I've gotten at lest 6 opportunities where I've added to cart and tried to checkout but it went out of stock. I've realized that if you can't beat'em, you might as well join them. Has anyone successfully gotten a PS5 with this bot? and does it only run when you tell it to or can it do it in the background?

**Comment by pythonishard** [comment]
you can run it in the background, it constantly refreshes the page and will automatically fill out checkout details

**Comment by VVNoodle** [comment]
It's still heavily in progress right now, so I would say don't rely on this bot just yet (check out #6) for more info. Optimistic me is confident that you can rely on this bot at least 1-2 days before Black Friday next week 🙂

**Comment by tsn-gh00** [comment]
TimeoutError: waiting for target failed: timeout 30000ms exceeded
    at Object.waitWithTimeout (H:\PS5bot\node_modules\puppeteer\lib\cjs\puppeteer\common\helper.js:224:26)
    at Browser.waitForTarget (H:\PS5bot\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:269:45)
    at ChromeLauncher.launch (H:\PS5bot\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:100:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by TheManWhoLikesToCode** [comment]
Tried with the walmart release today it flopped :(

**Comment by JimmyNunnally** [comment]
Did not work for Walmart. Ran into time out errors which is the same reason why I could not do it manually
